scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

    pipeline_stages:
    - regex:
        expression: '^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z) (?<level>[^ ]+) (?<message>.*)$'
    - timestamp:
        source: time
        format: RFC3339
    - labels:
        level: '{{ .level }}'

remote_write:
  - url: http://loki:3100/loki/api/v1/push
