version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    restart: unless-stopped
    user: "root:root"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafanaadmin 
    restart: unless-stopped
    user: "root:root"

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/data:/alertmanager/data
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki/data:/loki/data
    restart: unless-stopped

  promtail:
    image: grafana/promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/config.yaml:/etc/promtail/config.yaml
      - ./promtail/data:/promtail/data
      - /var/log:/var/log
    restart: unless-stopped
    user: "root:root"

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

