services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor_exporter
    restart: unless-stopped
    ports:
    - 7101:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  systemd_exporter:
    image: prom/systemd-exporter:latest
    container_name: systemd_exporter
    restart: unless-stopped
    ports:
      - 7102:9118
    volumes:
      - /run/systemd/journal:/run/systemd/journal:ro
      - /var/run/dbus:/var/run/dbus:ro
    privileged: true

#необходимо поместить в один докер компоуз файл с постгрес
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    restart: unless-stopped
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://login:password@container_name_with_postgres:5432/db_name?sslmode=disable
    networks:
      - internal
      - local


#у кликхауса нужно раскомментировать конфиг постгреса и указать порт, экспортер не нужен
  clickhouse_exporter:
    image: prom/clickhouse-exporter:latest
    container_name: clickhouse_exporter
    restart: unless-stopped
    ports:
      - "7104:9104" # Порт для экспорта метрик
    environment:
      - CLICKHOUSE_URL=http://clickhouse:9000 # URL подключения к ClickHouse (замените на ваш)
      - CLICKHOUSE_USER=default # Пользователь ClickHouse (замените на ваш)
      - CLICKHOUSE_PASSWORD=YOUR_CLICKHOUSE_PASSWORD # Пароль ClickHouse (замените на ваш)

###nginx exporter готов      
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:1.4.0
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    restart: always
    command:
      - -nginx.scrape-uri  #вот так вводить команды будет точно правильно 
      - http://192.168.0.116:80/nginx_status
    networks:
      - local
      - internal
###пока работает только в одном с kafka докер компоуз файле
 kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka_exporter
    command: ["--kafka.server=kafka:9092"]
    restart: unless-stopped
    ports:
      - 9308:9308

#необходимо поместить в один докер компоуз файл с редис
  redis-exporter-crm: 
    image: oliver006/redis_exporter:v1.45.0
    container_name: redis_exporter_crm
    restart: unless-stopped
    ports:
      - 9121:9121
    environment:
      REDIS_ADDR: redis://crm-redis:6379
      REDIS_PASSWORD: DFGWG7EwVmmxKPCtyKVge8oLd2t81211
    networks:
      - local

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: unless-stopped
    ports:
      - "7108:9115" # Порт для экспорта метрик
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml # Путь к конфигурационному файлу

  networks:
  internal:
    driver: bridge
  local:
    driver: bridge
