services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor_exporter
    restart: unless-stopped
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  systemd_exporter:
    image: prom/systemd-exporter:latest
    container_name: systemd_exporter
    restart: unless-stopped
    ports:
      - 9118:9118
    volumes:
      - /run/systemd/journal:/run/systemd/journal:ro
      - /var/run/dbus:/var/run/dbus:ro
    privileged: true

  postgres_exporter:
    image: prom/postgres-exporter:latest
    container_name: postgres_exporter
    restart: unless-stopped
    ports:
      - "9187:9187" # Порт для экспорта метрик
    environment:
      - POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD # Пароль пользователя PostgreSQL
      - POSTGRES_USER=YOUR_POSTGRES_USER # Пользователь PostgreSQL с правами на мониторинг
      - POSTGRES_HOST=YOUR_POSTGRES_HOST # Хост PostgreSQL
      - POSTGRES_PORT=YOUR_POSTGRES_PORT # Порт PostgreSQL

  clickhouse_exporter:
    image: prom/clickhouse-exporter:latest
    container_name: clickhouse_exporter
    restart: unless-stopped
    ports:
      - "9104:9104" # Порт для экспорта метрик
    environment:
      - CLICKHOUSE_URL=http://clickhouse:9000 # URL подключения к ClickHouse (замените на ваш)
      - CLICKHOUSE_USER=default # Пользователь ClickHouse (замените на ваш)
      - CLICKHOUSE_PASSWORD=YOUR_CLICKHOUSE_PASSWORD # Пароль ClickHouse (замените на ваш)

  nginx_exporter:
    image: prom/nginx-exporter:latest
    container_name: nginx_exporter
    restart: unless-stopped
    ports:
      - "9119:9119" # Порт для экспорта метрик
    environment:
      - NGINX_HOST=your-nginx-host # Хост Nginx (localhost, IP или имя хоста)
      - NGINX_PORT=80 # Порт Nginx (по умолчанию 80)  


 kafka_exporter:
    image: prom/kafka-exporter:latest
    container_name: kafka_exporter
    restart: unless-stopped
    ports:
      - "9120:9120" # Порт для экспорта метрик
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092 # Адреса брокеров Kafka (замените на ваши)

 redis_exporter:
    image: prom/redis-exporter:latest
    container_name: redis_exporter
    restart: unless-stopped
    ports:
      - "9121:9121" # Порт для экспорта метрик
    environment:
      - REDIS_ADDR=redis:6379 # Адрес Redis (замените на ваш)     

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: unless-stopped
    ports:
      - "9115:9115" # Порт для экспорта метрик
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml # Путь к конфигурационному файлу
