global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
         - targets: ["server_ip:9093"]

rule_files:
  - "rules.yml"


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['server_ip:9100'] # node_exporter
      - targets: ['server_ip:9100'] # promtail

#Работвть будет в докере, поэтому надо указывать внешний ip вместо example
