global:
  scrape_interval: 15s
  evaluation_interval: 15s
  query_log_file: /prometheus/prometheusquery.log

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['example:9090']
      - targets: ['example:9100']

#Работвть будет в докере, поэтому надо указывать внешний ip вместо example
